### ISSUE TITLE
Create smart test set for SearchSECO

### ISSUE THREAD

**Issue by slingerbv** [SecureSECO/searchSECO-miner#48]
Create several projects, that share methods with each other, to ensure that the project is testable. Currently, we have to guess that the project is working correctly. 

P1: M1, M2, M3
P2: M4, M5, M6
P3: M1, M2
P4: M1, M4, M7

**Comment by slingerbv** [comment]
Please note that all methods need to exceed at least X lines. I don't remember if X is 7 or less.

**Comment by slingerbv** [comment]
Please add links to your test sets here @aminuldidar ?

**Comment by aminuldidar** [comment]
Here is the link of test set:

https://docs.google.com/spreadsheets/d/175thQmypdZsd_O6fnq3G2jxqhHqIbt5O/edit?gid=695597247#gid=695597247

Automation has been done and committed as github action.
