### ISSUE TITLE
searchSECO-miner stopping with the error code 413

### ISSUE THREAD

**Issue by aminuldidar** [SecureSECO/searchSECO-miner#74]
| miner        | JsonRequest.js          35 | [ DEBUG ] Status code: 413
| miner        | JsonRequest.js          37 | [ WARN  ] JSON api status code: 413
| miner        | JsonRequest.js         222 | [ WARN  ] error message:  Error! status: 413
| miner        | Miner.js                53 | [ ERR   ] Miner exited with error Error: Error! status: 413. Restarting after 2 seconds...

**Comment by slingerbv** [comment]
Fixed in previous release.
